# Generated by Django 6.1.1 on 2026-09-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ("-published_date", "title")},
        ),
        migrations.AlterModelOptions(
            name="redactor",
            options={"ordering": ("first_name",)},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ("name",)},
        ),
        migrations.RenameField(
            model_name="newspaper",
            old_name="name",
            new_name="title",
        ),
    ]
