# Generated by Django 6.1.1 on 2026-10-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_newspaper_options_alter_redactor_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaper",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="published_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
